#ifndef AKINATOR_ERRORS_H
#define AKINATOR_ERRORS_H

enum akinator_error_t {
    AKINATOR_SUCCESS                        = 0,
    AKINATOR_EXIT_SUCCESS                   = 1,
    AKINATOR_TEXT_BUFFER_ALLOCATION_ERROR   = 2,
    AKINATOR_DATABASE_OPENING_ERROR         = 3,
    AKINATOR_DATABASE_READING_ERROR         = 4,
    AKINATOR_TREE_ALLOCATION_ERROR          = 5,
    AKINATOR_USER_ANSWER_ERROR              = 6,
    AKINATOR_GENERAL_DUMP_OPENING_ERROR     = 7,
    AKINATOR_DOT_FILE_OPENING_ERROR         = 8,
    AKINATOR_WRITING_DUMP_ERROR             = 9,
    AKINATOR_SYSTEM_COMMAND_ERROR           = 10,
    AKINATOR_TEXT_CONTAINERS_STORAGE_ERROR  = 11,
    AKINATOR_DEFINITION_ALLOCATING_ERROR    = 12,
    AKINATOR_LEAFS_ALLOCATING_ERROR         = 13,
};

#endif
