#ifndef AKINATOR_ERRORS_H
#define AKINATOR_ERRORS_H

enum akinator_error_t {
    AKINATOR_SUCCESS                        = 0,
    AKINATOR_EXIT_SUCCESS                   = 1,
    AKINATOR_TEXT_BUFFER_ALLOCATION_ERROR   = 2,
    AKINATOR_DATABASE_OPENING_ERROR         = 3,
    AKINATOR_DATABASE_READING_ERROR         = 4,
    AKINATOR_TREE_ALLOCATION_ERROR          = 5,
    AKINATOR_USER_ANSWER_ERROR              = 6,
    AKINATOR_GENERAL_DUMP_OPENING_ERROR     = 7,
    AKINATOR_DOT_FILE_OPENING_ERROR         = 8,
    AKINATOR_WRITING_DUMP_ERROR             = 9,
    AKINATOR_SYSTEM_COMMAND_ERROR           = 10,
    AKINATOR_TEXT_CONTAINERS_STORAGE_ERROR  = 11,
    AKINATOR_DEFINITION_ALLOCATING_ERROR    = 12,
    AKINATOR_LEAFS_ALLOCATING_ERROR         = 13,
    AKINATOR_MEMSET_ERROR                   = 14,
    AKINATOR_NULL_POINTER                   = 15,
    AKINATOR_NULL_USED_CONTAINER            = 16,
    AKINATOR_CONTAINERS_OVERFLOW            = 17,
    AKINATOR_NOT_NULL_UNUSED_CONTAINER      = 18,
    AKINATOR_NODE_NULL                      = 19,
    AKINATOR_ONE_CHILD                      = 20,
    AKINATOR_CHILD_PARENT_CONNECTION_ERROR  = 21,
    AKINATOR_NULL_ROOT                      = 22,
    AKINATOR_WAY_ARRAY_NULL                 = 23,
    AKINATOR_INVALID_NODE_LEVEL             = 24,
    AKINATOR_NULL_OBJECT_NAME               = 25,
    AKINATOR_ANSWER_NULL                    = 26,
    AKINATOR_DATABASE_FILENAME_NULL         = 27,
    AKINATOR_TEXT_TO_SPEECH_ERROR           = 28,
    AKINATOR_MESSAGE_SIZE_ERROR             = 29,
    AKINATOR_IMAGE_LOADING_ERROR            = 30,
    AKINATOR_UI_ENVIRONMENT_ERROR           = 31,
    AKINATOR_NULL_FUNCTION_PARAMETER        = 32
};

#endif
